language: python

install: pip install $DJANGO --use-mirrors

script:
  - python -c 'from __future__ import print_function; import django; print("Django {0}".format(django.get_version()))'
  - python setup.py test

matrix:
  include:
     - python: 2.6
       env: DJANGO="Django>=1.4,<1.5"
     - python: 2.7
       env: DJANGO="Django>=1.5,<1.6"
     - python: 3.2
       env: DJANGO="Django>=1.6,<1.7"
     - python: 3.3
       env: DJANGO="Django>=1.6,<1.7"
     - python: 3.4
       env: DJANGO="Django>=1.7,<1.8"
